services:
  killed-by-laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: killed-by-laravel-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    labels:
      caddy: killed-by-laravel.harkema.dev
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - caddy
    environment:
      - NODE_ENV=production

networks:
  caddy:
    external: true